language: julia
julia:
    - 1.0
    - 1.1
    - nightly
matrix:
    allow_failures:
    - julia: nightly
    fast_finish: true
notifications:
    email: false
after_success:
    - julia -e 'using Pkg; import PairingHeaps; cd(joinpath(dirname(pathof(PairingHeaps)), "..")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
