language: julia
julia:
    - 1.0
    - 1.1
    - nightly
matrix:
    allow_failures:
        - julia: nightly
    fast_finish: true
notifications:
    email: false
after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("PairingHeap")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
